### ISSUE TITLE
Problem with Postgresql db:migrate when deploy

### ISSUE THREAD

**Issue by unavailabl3** [capistrano/rails#230]
```
deploy:migrating
      01 /usr/local/rvm/bin/rvm default do bundle exec rake db:migrate
      01 rake aborted!
      01 PG::ConnectionBad: FATAL:  password authentication failed for user "customuser"
...
Tasks: TOP => db:migrate
```

1) I can normally login to psql under customuser
2) command on server` RAILS_ENV=production rake db:migrate` is workling
3) database.yml :
```
production:
  <<: *default
  database: app_production
  username: railsuser
  password: mypassword
```
4) /etc/postgresql/10/main/pg_hba.conf :
